project:
  type: website
  output-dir: docs

website:
  title: "Jocelyn's R Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://jgaray1.github.io/jg_first_blog/
      - icon: twitter
        href: https://twitter.com/
format:
  html:
    theme: vapor
    css: styles.css

editor: visual

